### ISSUE TITLE
[UPGRADE] ignore files by names

### ISSUE THREAD

**Issue by EwenSellitto** [Quentin-Desmettre/EpiLinter#6]
##  ignore files by names
Might be useful to have a ways to ignore some files.

### possibilities
Ignore files in the .Gitignore
Add a config file to ignore filename using regexes.

**Comment by Quentin-Desmettre** [comment]
Thank you for your feedback, this feature has just been released, check it out [here](https://github.com/Quentin-Desmettre/EpiLinter/releases/tag/Release) !
